name: CI/CD Pipeline

on:
  push:
    branches:[main]
  pull:
    branches:[main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -uses: actions/checkout@v3
        with:
        node-version : '18'

      -run: npm install
      -run: npm run build

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref  == 'refs/heads/main'
    steps:
      -name: deploy to render
      run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}